package dsw.gerumap.app.logger;

import lombok.NonNull;

public enum EventType {

    ADDING_ELEMENT,
    NON_SELECTED,
    FIELD_CANNOT_BE_EMPTY,
    ADD_AUTHOR_ERROR,
    REMOVE_PROJECT_EXPLORER,
    NON_SELECTED_STATE,
    NUMBERS_ONLY,
    CANNOT_BE_USED,
    OUT_OF_BOUNDS,
    ALREADY_SAVED,
    NON_SELECTED_PROJECT,
    NO_MAPVIEW,
    EMPTY_MINDMAP,
    ONLY_ONE_SELECTED,
    SAVE_AS_PROJECT,
    NON_CONNECTION;

}
